### ISSUE TITLE
Reasoning for use of functional components

### ISSUE THREAD

**Issue by dennis-every** [dennis-every/math-magicians#4]
Per [project requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_refactor_with_hooks.md), 

- If you already use functional components, you can create a GitHub issue in which you describe how you use functional components and ask for a code review based on your issue.
- As of React v16.8 it's recommended to only write functional components. You might see class components every once in a while, but it's discouraged to use them.
- Per React [docs](https://beta.reactjs.org/learn/your-first-component#step-2-define-the-function):
- React components are regular JavaScript functions except:
- Their names always begin with a capital letter.
- They return JSX markup.

Functional components are preferred over class components:
1. Functional components require less code which results in smaller file sizes.
2. Functional components promote composition over inheritance.
3. Functional components are stateless.

For this project, rather than using classes, we've defined the Calculator and Button components as functional components in their respective files.

**Comment by TadesseDev** [comment]
### Hi @dennis-every 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)



## Highlights

## Optional suggestions
- [Optional] would suggest you use an arrow function instead of an ordinary function syntax. This is to make your cod a bit simplified. 
#### something line...
```javascript
const Calculator = () => (
       <section id="calculator">
      </section >
);

```
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
